
## useful explanation of multiple issues with GCC builds
## https://liblfds.org/mediawiki/index.php?title=Building_GCC
## https://gmplib.org/list-archives/gmp-bugs/2010-December/002140.html

- name: Get GCC sources
  become: true
  get_url: url={{gcc_url}} dest={{gcc_tmp}} timeout=180 force=no
  register: gcc_downloaded

- name: Extract GCC sources
  become: true
  unarchive: src={{gcc_tmp}}
             dest="/tmp"
             creates={{gcc_build}}
             remote_src=yes
  when: gcc_downloaded.changed

- name: Download GMP MPFR and MPC
  become: true
  shell: chdir={{gcc_build}} ./contrib/download_prerequisites
  when: gcc_downloaded.changed

- name: Patch GMP bug
  become: true
  replace:
      path={{gcc_build}}/gmp/{{item}}
      regexp='M4=m4-not-needed'
      replace='M4=m4'
      backup=no
  with_items:
  - configure
  - configure.in

- name: Make gcc build folder
  become: true
  file: path={{gcc_build_dir}} state=directory
  when: gcc_downloaded.changed

- name: Configure GCC
  become: true
  shell: chdir={{gcc_build_dir}} {{gcc_build}}/configure \
    --prefix={{gcc_install_dir}} \
    --disable-nls \
    --enable-languages=c,c++ \
    --disable-multilib
  when: gcc_downloaded.changed

- name: Make GCC
  become: true
  shell: chdir={{gcc_build_dir}} make
  when: gcc_downloaded.changed

- name: Install GCC
  become: true
  shell: chdir={{gcc_build_dir}} make install
  when: gcc_downloaded.changed

# - name: Make libgcc
#   become: true
#   shell: chdir={{gcc_build_dir}} make all-target-libgcc

# - name: Install libgcc
#   become: true
#   shell: chdir={{gcc_build_dir}} make install-target-libgcc
