- name: Get binutils sources
  become: true
  get_url: url={{binutils_url}} dest={{binutils_tmp}} sha256sum={{binutils_sha256sum}} timeout=60

- name: Extract binutils sources
  become: true
  unarchive: src={{binutils_tmp}} dest="/tmp" creates={{binutils_build}} remote_src=yes

- name: Configure binutils
  become: true
  shell: chdir={{binutils_build}} ./configure --target={{gcc_target}} --prefix={{gcc_install_dir}} --disable-nls --disable-werror

- name: Make binutils
  shell: chdir={{binutils_build}} make

- name: Install binutils
  shell: chdir={{binutils_build}} make install

- name: wat
  debug: msg=ftp://ftp.fu-berlin.de/unix/languages/gcc/releases/gcc-{{gcc_version}}/gcc-{{gcc_version}}.tar.gz
