- name: Get GCC sources
  become: true
  get_url: url={{gcc_url}} dest={{gcc_tmp}} timeout=180

- name: Extract GCC sources
  become: true
  unarchive: src={{gcc_tmp}} dest="/tmp" creates={{gcc_build}} remote_src=yes

- name: Make gcc build folder
  become: true
  file: path={{gcc_build_dir}} state=directory


#### GMP
- name: Get GMP
  become: true
  get_url: url={{gmp_url}} dest={{gmp_tmp}} timeout=180
  register: gmp_downloaded

- name: Make GMP build folder
  become: true
  file: path={{gmp_build_dir}} state=directory
  when: gmp_downloaded.changed

- name: Extract GMP sources
  become: true
  unarchive: src={{gmp_tmp}} dest={{gmp_build_dir}} remote_src=yes
  when: gmp_downloaded.changed

- name: Configure GMP
  become: true
  shell: chdir={{gmp_build_dir}} ./configure --prefix={{gcc_build_dir}} --disable-shared  --enable-static
  when: gmp_downloaded.changed

- name: Make GMP
  become: true
  shell: chdir={{gmp_build_dir}} make && make check && make install
  when: gmp_downloaded.changed
##############


#### GMFR
- name: Get GMFR
  become: true
  get_url: url={{gmfr_url}} dest={{gmfr_tmp}} timeout=180
  register: gmfr_downloaded

- name: Make GMFR build folder
  become: true
  file: path={{gmfr_build_dir}} state=directory
  when: gmfr_downloaded.changed

- name: Extract GMFR sources
  become: true
  unarchive: src={{gmfr_tmp}} dest={{gmfr_build_dir}} remote_src=yes
  when: gmfr_downloaded.changed

- name: Configure GMFR
  become: true
  shell: chdir={{gmfr_build_dir}} ./configure --prefix={{gcc_build_dir}} --disable-shared  --enable-static --with-gmp={{gcc_build_dir}}
  when: gmp_downloaded.changed

- name: Make GMFR
  become: true
  shell: chdir={{gmfr_build_dir}} make && make check && make install
  when: gmfr_downloaded.changed
##############


#### MPC
- name: Get MCP
  become: true
  get_url: url={{mpc_url}} dest={{mpc_tmp}} timeout=180
  register: mpc_downloaded

- name: Make MPC build folder
  become: true
  file: path={{mpc_build_dir}} state=directory
  when: mpc_downloaded.changed

- name: Extract MPC sources
  become: true
  unarchive: src={{mpc_tmp}} dest={{mpc_build_dir}} remote_src=yes
  when: mpc_downloaded.changed

- name: Configure MPC
  become: true
  shell: chdir={{mpc_build_dir}} ./configure --prefix={{gcc_build_dir}} --disable-shared  --enable-static --with-gmp={{gcc_build_dir}} --with-gmfr={{gcc_build_dir}}
  when: mpc_downloaded.changed

- name: Make MPC
  become: true
  shell: chdir={{mpc_build_dir}} make && make check && make install
  when: mpc_downloaded.changed
##############



# ####### MPC
# - name: Get MPC
#   become: true
#   get_url: url={{mpc_url}} dest={{mpc_tmp}} timeout=180

# - name: Extract GMP sources
#   become: true
#   unarchive: src={{mpc_tmp}} dest="/tmp" remote_src=yes

# - name: Get MPFR
#   become: true
#   get_url: url={{mpfr_url}} dest={{mpfr_tmp}} timeout=180

# - name: Extract MPFR sources
#   become: true
#   unarchive: src={{mpfr_tmp}} dest="/tmp" remote_src=yes



# - name: Get Cloog
#   become: true
#   get_url: url={{cloog_url}} dest={{cloog_tmp}} timeout=180

# - name: Extract Cloog sources
#   become: true
#   unarchive: src={{cloog_tmp}} dest="{{cloog_build}}" remote_src=yes

# - name: Get ISL
#   become: true
#   get_url: url={{isl_url}} dest={{isl_tmp}} timeout=180

# - name: Extract ISL sources
#   become: true
#   unarchive: src={{isl_tmp}} dest="{{isl_build}}" remote_src=yes


# - name: Extract MPFR sources
#   become: true
#   unarchive: src={{mpfr_tmp}} dest="{{gcc_build_dir}}" creates="mpfr" remote_src=yes

# - name: Extract cloog sources
#   become: true
#   unarchive: src={{cloog_tmp}} dest="{{gcc_build_dir}}" creates="cloog" remote_src=yes

# - name: Extract ISL sources
#   become: true
#   unarchive: src={{isl_tmp}} dest="{{gcc_build_dir}}" creates="isl" remote_src=yes

# - name: Extract cloog sources
#   become: true
#   unarchive: src={{cloog_tmp}} dest="{{gcc_build_dir}}" creates="cloog" remote_src=yes


# - name: Download GMP MPFR and MPC
#   become: true
#   shell: chdir={{gcc_build}} ./contrib/download_prerequisites

- name: Configure GCC
  become: true
  shell: chdir={{gcc_build_dir}} {{gcc_build}}/configure \
    --prefix={{gcc_install_dir}} \
    --disable-shared \
    --enable-static \
    --disable-nls \
    --enable-languages=c,c++ \
    --disable-multilib \
    --with-gmp={{gcc_build_dir}} \
    --with-mpfr={{gcc_build_dir}} \
    --with-mpc={{gcc_build_dir}}

- name: Make GCC
  become: true
  shell: chdir={{gcc_build_dir}} make all-gcc
  # register: command_result
  # ignore_errors: True

# - name: Make libgcc
#   become: true
#   shell: chdir={{gcc_build_dir}} make all-target-libgcc

- name: Install GCC
  become: true
  shell: chdir={{gcc_build_dir}} make install-gcc

# - name: Install libgcc
#   become: true
#   shell: chdir={{gcc_build_dir}} make install-target-libgcc
