# - name: Get binutils sources
#   become: true
#   get_url: url={{binutils_url}} dest={{binutils_tmp}} sha256sum={{binutils_sha256sum}} timeout=60

# - name: Extract binutils sources
#   become: true
#   unarchive: src={{binutils_tmp}} dest="/tmp" creates={{binutils_build}} remote_src=yes

# - name: Configure binutils
#   become: true
#   shell: chdir={{binutils_build}} ./configure --prefix={{binutils_install_dir}} --disable-nls --disable-werror

# - name: Make binutils
#   shell: chdir={{binutils_build}}

# - name: Install binutils
#   shell: chdir={{binutils_build}} make install

# - name: wat
#   debug: msg=ftp://ftp.fu-berlin.de/unix/languages/gcc/releases/gcc-{{gcc_version}}/gcc-{{gcc_version}}.tar.gz

- name: Get GCC sources
  become: true
  get_url: url={{gcc_url}} dest={{gcc_tmp}} sha256sum={{gcc_sha256sum}} timeout=180

- name: Extract GCC sources
  become: true
  unarchive: src={{gcc_tmp}} dest="/tmp" creates={{gcc_build}} remote_src=yes

- name: Make gcc build folder
  become: true
  file: path={{gcc_build_dir}} state=directory

- name: Download GMP MPFR and MPC
  become: true
  shell: chdir={{gcc_build}} ./contrib/download_prerequisites

- name: Symlink binutils
  become: true
  shell: ln -s -f {{binutils_build}}/* {{gcc_build}}/
  # file: src={{ item }} dest={{gcc_build}}/{{ item | basename }} state=link
  # with_fileglob: {{binutils_build}}/*

- name: Configure GCC
  become: true
  shell: chdir={{gcc_build_dir}} {{gcc_build}}/configure --prefix={{gcc_install_dir}} --disable-nls --enable-languages=c --without-headers

- name: Make GCC
  become: true
  shell: chdir={{gcc_build_dir}} make all-gcc

- name: Make libgcc
  become: true
  shell: chdir={{gcc_build_dir}} make all-target-libgcc

- name: Install GCC
  become: true
  shell: chdir={{gcc_build_dir}} make install-gcc

- name: Install libgcc
  become: true
  shell: chdir={{gcc_build_dir}} make install-target-libgcc
