---

# https://www.vultr.com/docs/how-to-install-gdb-on-centos-6

- name: GDB | check if gbd was already instaled
  stat:
    path: "{{ gdb_install_dir }}/bin/gdb"
  register: gdb_exists

- name: GDB | get sources
  become: true
  get_url: url={{gdb_url}} dest={{gdb_tmp}} timeout=180
  when: not gdb_exists.stat.exists
  register: gdb_downloaded

- name: GDB | Extract sources
  become: true
  unarchive: src={{gdb_tmp}} dest="/tmp" creates={{gdb_build}} remote_src=yes
  when: gdb_downloaded.changed
  register: gdb_extract

- name: GDB | Configure
  become: true
  shell: chdir={{gdb_build}} \
              ./configure \
              --with-python=yes \
              --prefix={{gdb_install_dir}} \
              --disable-werror
  when: gdb_extract.changed
  register: gdb_configure

- name: GDB | Make
  become: true
  shell: chdir={{gdb_build}} make
  when: gdb_configure.changed
  register: gdb_make

- name: GDB | Install
  become: true
  shell: chdir={{gdb_build}} make install
  when: gdb_make.changed
  register: gdb_install

- name: GDB | cleanup build
  become: true
  file:
    path: "{{ gdb_build_dir }}"
    state: absent
  when: gdb_install.changed

- name: GDB | cleanup tmp
  become: true
  file:
    path: "{{ gdb_tmp }}"
    state: absent
  when: gdb_install.changed
...
