- name: Get GCC sources
  become: true
  get_url: url={{gcc_url}} dest={{gcc_tmp}} timeout=180

- name: Extract GCC sources
  become: true
  unarchive: src={{gcc_tmp}} dest="/tmp" creates={{gcc_build}} remote_src=yes

- name: Make gcc build folder
  become: true
  file: path={{gcc_build_dir}} state=directory

- name: Download GMP MPFR and MPC
  become: true
  shell: chdir={{gcc_build}} ./contrib/download_prerequisites

- name: Configure GCC
  become: true
  shell: chdir={{gcc_build_dir}} {{gcc_build}}/configure --prefix={{gcc_install_dir}} --disable-nls --enable-languages=c,c++ --disable-multilib

- name: Make GCC
  become: true
  shell: chdir={{gcc_build_dir}} make all-gcc
  register: command_result
  ignore_errors: True

# - name: Make libgcc
#   become: true
#   shell: chdir={{gcc_build_dir}} make all-target-libgcc

- name: Install GCC
  become: true
  shell: chdir={{gcc_build_dir}} make install-gcc

# - name: Install libgcc
#   become: true
#   shell: chdir={{gcc_build_dir}} make install-target-libgcc
