# - name: Get GCC sources
#   become: true
#   get_url: url={{gcc_url}} dest={{gcc_tmp}} timeout=180
#   register: gcc_downloaded

- name: Get and Extract GCC sources
  become: true
  unarchive: src={{gcc_url}}
             dest="/tmp"
             copy=no
             # creates={{gcc_build}}
             # remote_src=yes
  # when: gcc_downloaded.changed
  register: gcc_downloaded

- name: Make gcc build folder
  become: true
  file: path={{gcc_build_dir}} state=directory
  when: gcc_downloaded.changed

- name: Download GMP MPFR and MPC
  become: true
  shell: chdir={{gcc_build}} ./contrib/download_prerequisites
  when: gcc_downloaded.changed

- name: Configure GCC
  become: true
  shell: chdir={{gcc_build_dir}} {{gcc_build}}/configure \
    --prefix={{gcc_install_dir}} \
    --disable-nls \
    --enable-languages=c,c++ \
    --disable-multilib
  when: gcc_downloaded.changed

- name: Make GCC
  become: true
  shell: chdir={{gcc_build_dir}} make
  when: gcc_downloaded.changed

- name: Install GCC
  become: true
  shell: chdir={{gcc_build_dir}} make install
  when: gcc_downloaded.changed

# - name: Make libgcc
#   become: true
#   shell: chdir={{gcc_build_dir}} make all-target-libgcc

# - name: Install libgcc
#   become: true
#   shell: chdir={{gcc_build_dir}} make install-target-libgcc
