# tasks/main.yml

- name: Make sure the packages are installed (Fedora)
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - gcc
  - gcc-c++
  - make
  - openssl-devel
  when: ansible_os_family == "Centos"
