# tasks/main.yml

- name: Install GCC and Clang
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - gcc
  - gcc-c++
  - clang
  - make
  - openssl-devel
  # when: ansible_os_family == "Centos"
